const data = {
    products: [
      {
        name: 'Silver Eastern Nackless',
        unique_indentity: 'Silver Eastern Nackless',
        category: 'jwellery',
        image: 'https://th.bing.com/th/id/OIP.B7cqaJ_L9yOOi3kVhbsiWADYEg?w=140&h=186&c=7&r=0&o=5&dpr=1.3&pid=1.7', // 679px × 829px
        price: 120,
        countInStock: 10,
        brand: 'Giva',
        rating: 4.5,
        numReviews: 10,
        description: 'Giva Silver Eastern Nackless',
      },
      {
        name: 'Mirenda gold ring',
        unique_indentity: 'Mirenda gold ring',
        category: 'Jwellery',
        image: 'https://th.bing.com/th?id=OPA.3vsp%2fiKgm%2fi1UA474C474&w=200&h=220&rs=1&o=5&dpr=1.3&pid=21.1',
        price: 250,
        countInStock: 20,
        brand: 'Mirenda',
        rating: 4.0,
        numReviews: 10,
        description: 'Gold Ring',
      },
      {
        name: 'Diamond pended',
        unique_indentity: 'diamond patend',
        category: 'jwellery',
        image: 'https://th.bing.com/th/id/OPA.z7JWmIlGVFyh5Q474C474?w=198&h=198&rs=1&o=5&dpr=1.3&pid=21.1',
        price: 25,
        countInStock: 15,
        brand: 'Evan',
        rating: 4.5,
        numReviews: 14,
        description: 'evan diamond pendend',
      },
      {
        name: 'Gold bangles',
        unique_indentity: 'gold bangles',
        category: 'jwellery',
        image: 'https://th.bing.com/th/id/OIP._dp1kPI9ySlax1gs1oy_3QHaE8?pid=ImgDet&rs=1',
        price: 65,
        countInStock: 5,
        brand: 'bahraini',
        rating: 4.5,
        numReviews: 10,
        description: 'bahraini golden bangles',
      },
      {
        name: 'Diamond Ring',
        unique_indentity: 'diamond Ring',
        category: 'jwellery',
        image: 'https://th.bing.com/th/id/OPA.WLiFRSjIYaalow474C474?o=5&pid=21.1&w=160&h=192&dpr=1.3',
        price: 65,
        countInStock: 5,
        brand: 'Yana',
        rating: 4.5,
        numReviews: 10,
        description: 'Yana Diamond Ring',
      },
    ],
  };
  export default data;